### ISSUE TITLE
Shoutbox not working for custom group

### ISSUE THREAD

**Issue by myblackrx** [XoopsModules25x/shoutbox#5]
Admin and Registered User can access the Shoutbox

But for a user with custom group other than the default group 

the user will see our xoops site in the Shoutbox block like inside iframe with the message No Permission to access the area

Permission to block and module has been granted in the Group Permission to the custom group but still having this problem

XOOPS Version	XOOPS 2.5.8
PHP Version	5.4.27
mySQL Version	5.5.36

Shoutbox 5.01
https://xoops.org/modules/newbb/viewtopic.php?post_id=362978&keywords=Shoutbox

https://xoops.org/modules/newbb/viewtopic.php?post_id=359350&keywords=Shoutbox

**Comment by mambax7** [comment]
Found the bug , solution coming soon....
